name: compile
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ci

    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0
        
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.5
      - name: Lista arquivos alterados.
        id: change-files
        run: |
            REPO_ROOT=$(git rev-parse --show-toplevel)
            # List files changed in the last commit compared to its parent (HEAD^1)
            # and prepend the absolute path.
            CHANGED_FILES=$(git diff --name-only HEAD^1 HEAD | sed "s|^|$REPO_ROOT/|")

            # Export the list as a step output (useful for subsequent steps)
            echo "changed_files_list<<EOF" >> $GITHUB_OUTPUT
            echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT    
        shell: bash

      - name: Compile
        env:
          CHANGES_FILES: "${{ steps.change-files.outputs.changed_files_list }}"
        run: |
            bun install
            bun index.ts