name: compile
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ci

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v6
        with:
          python-version: "3.12.3"
          cache: 'pip'
      - name: Criar lista de arquivos alterados.
        id: changed-files
        run: |
          REPO_ROOT=$(git rev-parse --show-toplevel)
          # List files changed in the last commit compared to its parent (HEAD^1)
          # and prepend the absolute path.
          CHANGED_FILES=$(git diff --name-only HEAD^1 HEAD | sed "s|^|$REPO_ROOT/|")

          # Export the list as a step output (useful for subsequent steps)
          echo "changed_files_list<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        shell: bash

      - name: Enviando arquivos alterados para compilação
        env:
          CHANGED_FILES: "${{ steps.changed-files.outputs.changed_files_list }}"
          BASE_API_COMPILAR: "${{env.BASE_API_COMPILAR }}"
        run: |
          pip install -r requirements.txt --break-system-packages
          python3 compile.py
