name: compile
on:
  push:
    branches: [master, staging]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./.ci

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v6
        with:
          python-version: "3.12.3"
          cache: "pip"

      - name: Extrair o nome da branch
        id: extract_branch
        shell: bash
        run: |
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Criar lista de arquivos alterados.
        id: changed-files
        shell: bash
        run: |
          REPO_ROOT=$(git rev-parse --show-toplevel)
          # List files changed in the last commit compared to its parent (HEAD^1)
          # and prepend the absolute path.
          CHANGED_FILES=$(git diff --name-only HEAD^1 HEAD | sed "s|^|$REPO_ROOT/|")

          # Export the list as a step output (useful for subsequent steps)
          echo "changed_files_list<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Instalando dependências
        run: |
          pip install -r requirements.txt --break-system-packages

      - name: Enviando arquivos alterados para compilação
        env:
          CHANGED_FILES: "${{ steps.changed-files.outputs.changed_files_list }}"
          BRANCH: "${{ steps.extract_branch.outputs.branch }}"
          X_SECRET: "${{ secrets.X_SECRET }}"
          BASE_API_CI_PROD: "${{ secrets.BASE_API_CI_PROD }}"
          BASE_API_CI_STAGING: "${{ secrets.BASE_API_CI_STAGING }}"
          NAMESPACE: "${{ secrets.NAMESPACE }}"
        run: |
          python3 compile.py
